name: "third_autocorrelation_inequality"

problem_spec:
  program_path: "../maths/third_autocorrelation_inequality/initial_program.py"
  problem_description: |
    Act as an expert software developer and mathematician specializing in
    searching for step functions with certain properties.

    Your task is to find a sequence of heights of a step function that
    maximizes the following score function (this is already implemented elsewhere
    in the code, you need not reimplement this):

    def sequence_score(sequence: np.ndarray) -> float:
      sequence = np.clip(np.array(sequence, dtype=np.float64), -1, 1)
      convolution = np.convolve(sequence, sequence)
      denominator = np.sum(sequence) ** 2
      if denominator < 0.01:
        return -np.inf
      return -len(sequence) * np.max(abs(convolution)) / denominator

    Your task is to write a search function that searches for the best sequence.
    Your search function has a time limit of 1000 seconds.

    You may code up any search method you want, and you are allowed to call the
    sequence_score() function as many times as you want.

    You may want to start your search from the best construction found so
    far, which you can access through the `init_sequence` argument.

  main_metric_name: "score"

budget:
  num_llm_calls: 100
  num_coroutines: 4

modules:
  database: GreedyAndIslandsDatabase
  prompt_sampler: TemplatePromptSampler
  llm: GenAILLMClient
  evaluator: DockerEvaluator
  logger: LocalLogger
